const titlesArr = [
  'Shadow Dragon / New Mystery',
  'Shadow Dragon / New Mystery Extra',
  'Shadows of Valentia',
  'Shadows of Valentia Extra',
  'Genealogy of the Holy War',
  'Genealogy of the Holy War Extra',
  'Thracia 776',
  'Thracia 776 Extra',
  'Binding Blade',
  'Binding Blade Extra',
  'Blazing Blade',
  'Blazing Blade Extra',
  'Sacred Stones',
  'Sacred Stones Extra',
  'Path of Radiance / Radiant Dawn',
  'Path of Radiance / Radiant Dawn Extra',
  'Awakening',
  'Awakening Extra',
  'Fates',
  'Fates Extra',
  'Three Houses',
  'Three Houses Extra',
  'Three Hopes',
  'Three Hopes Extra',
  'TMS#FE',
  'TMS#FE Extra',
  'Warriors',
  'Heroes',
  'Cipher'
]
const romhacksArr = [
  "The Last Promise",
  "The Last Promise Extra",
  "Vision Quest",
  "Vision Quest Extra",
  "Four Kings",
  "Four Kings Extra",
  "Code of the Burger King",
  "Code of the Burger King Extra",
  "Dark Lord and the Maiden of Light",
  "Dark Lord and the Maiden of Light Extra",
]
const filtersArr = [
  "Male",
  "Female",
  "Lords",
  "Avatars",
  "Refreshers",
  "Pegasus Knights",
  "Archers",
  "Healers",
  "Myrmidons",
  "Shapeshifters",
  "Wyvern Riders",
  "Armor Knights",
  "Red / Orange",
  "Pink",
  "Blue",
  "Purple",
  "Green",
  "Blonde",
  "Brown",
  "Black",
  "White / Gray",
  "Bald"
]
const doublesKeep = [
  'palla_sov',
  'catria_sov',
  'est_sov',
  'karel_fe6',
  'bartre_fe6',
  'marcus_fe6',
  'eliwood_fe7',
  'hector_fe7',
  'murdock_fe6',
  'guinivere_fe6',
  'zephiel_fe6',
  "merlinus_fe6",
  "leif_fe5",
  "nanna_fe5",
  "finn_fe5",
  "ced_fe5",
  "diarmuid_fe5"
]
const doublesRemove = [
  'palla_fe1',
  'catria_fe1',
  'est_fe1',
  'karel_fe7',
  'bartre_fe7',
  'marcus_fe7',
  'eliwood_fe6',
  'hector_fe6',
  'murdock_fe7',
  'guinivere_fe7',
  'zephiel_fe7',
  "merlinus_fe7",
  "leif_fe4",
  "nanna_fe4",
  "finn_fe4",
  "ced_fe4",
  "diarmuid_fe4"
]
const spoilerKeep = [
  'owain',
  'severa',
  'inigo',
  'edelgard_academy',
  'edelgard_war',
  'jeritza',
  'rhea',
  'sephiran_por',
  'sephiran_rd',
  'zelgius_por',
  'zelgius_rd',
  'sirius',
  'camus',
  'camus',
  'renning_por',
  'renning_rd',
  'brigid',
  'tiki_fe13',
  'thales'
]
const spoilerRemove = [
  'odin',
  'selena_fates',
  'laslow',
  'flame_emperor',
  'flame_emperor',
  'death_knight',
  'seiros',
  'lehran',
  'lehran',
  'black_knight_por',
  'black_knight_rd',
  'zeke',
  'sirius',
  'zeke',
  'bertram',
  'bertram',
  'eyvel',
  'tiki_fe1',
  'lord_arundel'
]
const otherGamesArr = [
  "Triangle Strategy",
  "Triangle Strategy Extra"
]